### ISSUE TITLE
Commutativity of addition does not terminate

### ISSUE THREAD

**Issue by TonitaN** [poitin/Distiller#13]
Hi Geoff,
the following example forces the distiller into an infinite loop:
```
main = (uequal (uadd x y) (uadd y x));

uadd x y = case x of
		Z -> y
	      | S(xs) -> (uadd xs S(y));

uequal x y = case x of
                Z -> (case y of
                         Z -> True
                       | S(ys) -> False)
              | S(xs) -> (case y of
                             Z -> True
                           | S(ys) -> (uequal xs ys))
```

**Comment by poitin** [comment]
Hi Antonina,

Thanks for this. There is currently a problem with my implementation of distillation when there are non-linear variables (caused by information propagation). I do not have a lot of time to sort this just now, but it is on my todo list;-)

**Comment by TonitaN** [comment]
Ahaha, the `uequal` function is actually `equal or greater than`. That has no impact on the termination, though.
Yes, the multiple dynamic variable occurrences are nasty, but I still hope that we will beat them some time ^_^

**Comment by poitin** [comment]
Finally got a chance to look at this - the distiller now terminates for this program.
