### ISSUE TITLE
Too many `f` names

### ISSUE THREAD

**Issue by Mazdaywik** [poitin/Distiller#15]
Source program contains `f` variable in entry point:
```
main = map f xs;

map g xs =
  case xs of
      Nil -> Nil
    | Cons(x, xs1) -> Cons(g x, map g xs1)
```
Residual program contains two `f` names: name of variable in source and name of generated function:
```
main = f xs f;
f xs f = case xs of
            Nil -> []
          | Cons(x,xs1) -> Cons(f x,f xs1 f)
```
For reducing confusion new generated functions should have names different from variables in entry point.

**Comment by poitin** [comment]
This now works correctly.
